CREATE DATABASE BANK_INFO
USE BANK_INFO
CREATE TABLE BORROW
(
	LOANNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	AMOUNT DECIMAL(8,2)
)
INSERT INTO BORROW
VALUES('481','KRANTI','NEHRUPLACE','3000.00')

SELECT*FROM BORROW