CREATE TABLE EMPLOYEE
(EID INT,
ENAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY DECIMAL (8,2),
JOININGDATE DATETIME,
CITY VARCHAR(50)
);
INSERT INTO EMPLOYEE
VALUES(101,'RAHUL','ADMIN',56000,'1990-JAN-01','RAJKOT');
SELECT*FROM EMPLOYEE
DELETE FROM EMPLOYEE 
WHERE EID = 101
INSERT INTO EMPLOYEE
VALUES(102,'HARDIK','IT',18000,'1990-SEP-25','AHMEDABAD');
SELECT*FROM EMPLOYEE
INSERT INTO EMPLOYEE
VALUES(103,'BHAVIN','HR',25000,'1991-MAY-14','BARODA');
SELECT*FROM EMPLOYEE

INSERT INTO EMPLOYEE
VALUES(104,'BHOOMI','ADMIN',39000,'1991-FEB-08','RAJKOT');
SELECT*FROM EMPLOYEE

INSERT INTO EMPLOYEE
VALUES(105,'ROHIT','IT',17000,'1990-JUL-23','JAMNAGAR');
SELECT*FROM EMPLOYEE

INSERT INTO EMPLOYEE
VALUES(106,'PRIYA','IT',9000,'1990-OCT-18','AHMEDABAD');
SELECT*FROM EMPLOYEE

INSERT INTO EMPLOYEE
VALUES(107,'NEHA','HR',34000,'1991-DEC-25','RAJKOT');
SELECT*FROM EMPLOYEE

SELECT MAX(SALARY) AS MAXIMUM,
		MIN(SALARY) AS MINIMUM,
		SUM(SALARY) AS TOTAL_SAL,
		AVG(SALARY) AS AVERAGE_SAL FROM EMPLOYEE

SELECT COUNT(*) 
FROM EMPLOYEE

SELECT DEPARTMENT,MAX(SALARY) AS SALARY 
FROM EMPLOYEE
WHERE DEPARTMENT = 'IT'
GROUP BY DEPARTMENT


SELECT COUNT(DISTINCT CITY) AS UNI_CITY
FROM EMPLOYEE

SELECT CITY,COUNT(*) AS TOTAL 
FROM EMPLOYEE
GROUP BY CITY

SELECT CITY,COUNT(*)
FROM EMPLOYEE
GROUP BY CITY
HAVING COUNT(*)>1

SELECT DEPARTMENT,SUM(SALARY) AS TOTAL
FROM EMPLOYEE
GROUP BY DEPARTMENT


SELECT DEPARTMENT,AVG(SALARY) AS DEPARTMENT_NAME
FROM EMPLOYEE
GROUP BY DEPARTMENT

SELECT MIN(SALARY) AS MINIMUM
FROM EMPLOYEE
WHERE CITY ='AHMEDABAD'

SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SAL
FROM EMPLOYEE
WHERE CITY = 'RAJKOT'
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>50000



SELECT COUNT(*) AS TOTAL_SAL
FROM EMPLOYEE
WHERE CITY = 'RAJKOT'

SELECT MAX(SALARY)-MIN(SALARY) AS SAL_DIFFERENCE
FROM EMPLOYEE

SELECT COUNT(*) AS DT
 FROM EMPLOYEE
 WHERE JOININGDATE <'1991-JAN-01'

 SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SAL
 FROM EMPLOYEE
 GROUP BY DEPARTMENT
 HAVING SUM(SALARY)>35000
 ORDER BY SUM (SALARY)

 SELECT DEPARTMENT , COUNT(*)
 FROM EMPLOYEE
 GROUP BY DEPARTMENT 
 HAVING COUNT(*)>2

 SELECT MIN(SALARY) AS TOTAL_SAL
 FROM EMPLOYEE
 WHERE CITY ='RAJKOT'

 SELECT  DEPARTMENT,MIN(SALARY) AS MINIMUM
 FROM EMPLOYEE
 GROUP BY DEPARTMENT

 SELECT  SUM(SALARY) AS TOTAL_SUM
 FROM EMPLOYEE
 GROUP BY CITY

 SELECT  DEPARTMENT,
 MIN(SALARY) AS MINIMUM,
 MAX (SALARY) AS MAXIMUM,
 SUM(SALARY) AS TOTAL_SUM
 FROM EMPLOYEE
 GROUP BY DEPARTMENT

 SELECT CITY ,DEPARTMENT , MAX(SALARY) AS MAXIMUM,
	MIN(SALARY) AS MINIMUM
	FROM EMPLOYEE
	GROUP BY CITY,DEPARTMENT 
	HAVING MAX(SALARY)<30000 