SELECT *
FROM STUDENT,RESULT 

SELECT 
		STUDENT.RNO,
		STUDENT.NAME,
		STUDENT.BRANCH,
		RESULT.SPI
FROM STUDENT
INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE STUDENT.BRANCH='CE'

SELECT 
		STUDENT.RNO,
		STUDENT.NAME,
		STUDENT.BRANCH,
		RESULT.SPI
FROM STUDENT
INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE STUDENT.BRANCH<>'EC'

SELECT 
	AVG(RESULT.SPI),
	STUDENT.BRANCH
FROM STUDENT
INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
GROUP BY STUDENT.BRANCH

 
SELECT 
	AVG(RESULT.SPI),
	STUDENT.BRANCH
FROM STUDENT
INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
GROUP BY BRANCH
ORDER BY AVG(RESULT.SPI)

SELECT 
	AVG(RESULT.SPI),
	STUDENT.BRANCH
FROM STUDENT
INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE BRANCH='CE' AND BRANCH='ME'
GROUP BY STUDENT.BRANCH
