SELECT 5*30
SELECT ABS(25)
SELECT  ABS(-25)
SELECT  ABS(-50)
SELECT  ABS(50)
SELECT CEILING(25.2)
SELECT CEILING(25.7)
SELECT CEILING(-25.2)
SELECT FLOOR(25.2)
SELECT FLOOR(25.7)
SELECT FLOOR(-25.2)
SELECT (5%2)
SELECT (5%3)
SELECT POWER(3,2)
SELECT POWER(4,3)
SELECT SQRT(25)
SELECT SQRT(30)
SELECT SQRT(50)
SELECT SQUARE(5)
SELECT SQUARE(15)
SELECT SQUARE(25)
SELECT PI()
SELECT ROUND(157.732,2)
SELECT ROUND(157.732,0)
SELECT ROUND(157.732,-2)
SELECT EXP(2)
SELECT EXP(3)
SELECT LOG(5,10)
SELECT LOG(5,100)
SELECT SIN (3.1415)
SELECT COS(3.1415)
SELECT TAN(3.1415)
SELECT SIGN(-25)
SELECT SIGN(0)
SELECT SIGN(25)
SELECT RAND()




SELECT LEN (NULL)
SELECT LEN('HELLO')
SELECT LEN('')

SELECT LOWER('KRISHA')
SELECT UPPER('KRISHA')

SELECT LEFT('KRISHA',3)

SELECT SUBSTRING('KRISHA',3,10)

Select REPLACE('abc123efg',123,'XYZ'), REPLACE('abcabcabc','c',5)
 
SELECT ASCII('a')
SELECT ASCII('A')
SELECT ASCII('z')
SELECT ASCII('Z')
SELECT ASCII('0')
SELECT ASCII('9')

SELECT CHAR (97)
SELECT CHAR (65)
SELECT CHAR (122)
SELECT CHAR (90)
SELECT CHAR (48)
SELECT CHAR (57)

SELECT LTRIM('HELLO WORLD')

SELECT RTRIM('HELLO WORLD')

Select LEFT ('sql server',4), RIGHT ('sql server',5) 

SELECT CAST(1234.56 AS FLOAT)

SELECT CONVERT(INT,10.58)

SELECT SPACE(10)+'KRISHA'

SELECT CONCAT('PADALIYA','KRISHA')
SELECT ('KRISHA'+'PADALIYA')

SELECT REVERSE('DARSHAN')

SELECT REPLICATE('KRISHA',3)

SELECT STUFF('KRISHA',1,3,'HTML')       

SELECT COALESCE(NULL,Null,'KRISHA')
SELECT COALESCE(NULL,'PADALIYA','KRISHA')

SELECT ISNUMERIC('32.7')
SELECT ISNUMERIC('KRISHA') 

SELECT CHARINDEX('T','CUSTOMER')
SELECT CHARINDEX('I','ADMISSION',5)




